{% set name = "boltons" %}
{% set version = "24.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a49b7d57ee055b83a458c8682a2a6f199d263a8aa517098bda9bab813554b87

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  source_files:
    - boltons
    - tests
    - pytest.ini
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - python -m pip check
    - python -m pip show boltons
    - pytest --doctest-modules boltons tests

about:
  home: https://github.com/mahmoud/boltons
  license: BSD-3-Clause
  license_file: LICENSE
  summary: When they're not builtins, they're boltons.
  description: |
    Functionality that should be in the standard library. Like builtins, but Boltons.

    Otherwise known as, “everyone’s util.py,” but cleaned up and tested.

    Contains over 250 BSD-licensed utility types and functions that can be used as a package or independently. Extensively documented on Read the Docs.

extra:
  recipe-maintainers:
    - kalefranz
    - nicoddemus
