{% set name = "boltons" %}
{% set version = "16.5.1" %}
{% set hash_type = "sha256" %}
{% set hash = "abca5976135e4ec1533158da1de88a66e05a650a184dc9bcbc2a83cbaf9a64fc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: '{{ version }}.tar.gz'
  url: https://github.com/mahmoud/boltons/archive/{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  source_files:
    - boltons
    - tests
  requires:
    - pytest
  commands:
    - 'py.test --doctest-modules boltons tests'

about:
  home: https://github.com/mahmoud/boltons
  license: BSD 3-Clause
  summary: >
    boltons should be builtins. Boltons is a set of over 160 BSD-licensed,
    pure-Python utilities in the same spirit as--and yet conspicuously
    missing from--the standard library.

extra:
  recipe-maintainers:
    - kalefranz
    - nicoddemus
