context:
  name: boltons
  version: 24.0.0
  hash: f55bb241f15be5761803216ae7509e9270faf8e3e8687e744ab61a401ddd20ff

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/mahmoud/boltons/archive/${{ version }}.tar.gz
  sha256: ${{ hash }}

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - files:
      source:
        - boltons
        - tests
        - pytest.ini
    requirements:
      run:
        - pytest
        - python ${{ python_min }}.*
    script:
      - pytest --doctest-modules boltons tests

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Boltons should be builtins. 
  description: Boltons is a set of over 160 BSD-licensed, pure-Python utilities in the same spirit as--and yet conspicuously missing from--the standard library.
  homepage: https://github.com/mahmoud/boltons

extra:
  recipe-maintainers:
    - kalefranz
    - nicoddemus
